name: 'Update Open in VSCode Link'
description: 'Parses README and updates the Open in VSCode link to current repository.'

runs:
  using: "composite"
  steps:
    - run: |
        if [[ -e README.md ]]; then
          sed -i 's~svg)](https://open.vscode.dev/.*)~svg)](https://open.vscode.dev/${{ github.repository }})~g' README.md
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "${{ github.actor }}"
          git add README.md
          git commit -m "Updated Open in VSCode link" || exit 0
          git push
        else
          echo "README not found."
        fi
      shell: bash
